In [2]:
import pandas as pd
import numpy as np

In [77]:
data = pd.read_csv('data_lake.csv')

/var/folders/7v/bgztryy15y1fjgx41y8zp4vc0000gn/T/ipykernel_24223/3717301982.py:1: DtypeWarning: Columns (3,4,6,7,8,9,10,11,15,16,17,18,21,22,24,25,27,28,29,30,31) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('data_lake.csv')

In [78]:
data

,Unnamed: 0.1,Unnamed: 0,item_id,name,category,price,old_price,sellable_online,link,other_colors,...,no_of_reviews,ratings,author,cover_type,year,genre,date,product,market,size
0,0,0.0,90420332.0,FREKVENS,Bar furniture,265.0,No old price,True,https://www.ikea.com/sa/en/p/frekvens-bar-tabl...,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1.0,368814.0,NORDVIKEN,Bar furniture,995.0,No old price,False,https://www.ikea.com/sa/en/p/nordviken-bar-tab...,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2.0,9333523.0,NORDVIKEN / NORDVIKEN,Bar furniture,2095.0,No old price,False,https://www.ikea.com/sa/en/p/nordviken-nordvik...,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,3.0,80155205.0,STIG,Bar furniture,69.0,No old price,True,https://www.ikea.com/sa/en/p/stig-bar-stool-wi...,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,4.0,30180504.0,NORBERG,Bar furniture,225.0,No old price,True,https://www.ikea.com/sa/en/p/norberg-wall-moun...,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92510,61927,NaN,NaN,NaN,NaN,3099.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-08,Yogurt,Nomin,liter
92511,61928,NaN,NaN,NaN,NaN,3100.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-08,Yogurt,Orgil,liter
92512,61929,NaN,NaN,NaN,NaN,3100.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-08,Yogurt,Sansar,liter
92513,61930,NaN,NaN,NaN,NaN,2900.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-08,Yogurt,Saruul,liter
92514,61931,NaN,NaN,NaN,NaN,3000.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-12-08,Yogurt,Tavan Erdene,liter

In [79]:
# Check columns containing missing values
data.columns[data.isna().any()].tolist()

['Unnamed: 0',
 'item_id',
 'name',
 'category',
 'price',
 'old_price',
 'sellable_online',
 'link',
 'other_colors',
 'short_description',
 'designer',
 'depth',
 'height',
 'width',
 'Pokemon',
 'Card Type',
 'Generation',
 'Card Number',
 'Price',
 'ranks',
 'title',
 'no_of_reviews',
 'ratings',
 'author',
 'cover_type',
 'year',
 'genre',
 'date',
 'product',
 'market',
 'size']

In [80]:
# Check the number of missing values (NaN) values in each column
missing_values = data.isnull().sum()
missing_values

Unnamed: 0.1             0
Unnamed: 0           87530
item_id              88821
name                 88821
category             88821
price                40829
old_price            88821
sellable_online      88821
link                 88821
other_colors         88821
short_description    88821
designer             88821
depth                90284
height               89809
width                89410
Pokemon              66917
Card Type            66917
Generation           66917
Card Number          66917
Price                66917
ranks                91228
title                91229
no_of_reviews        91228
ratings              91228
author               91229
cover_type           91229
year                 91224
genre                91227
date                 30583
product              30583
market               30583
size                 30583
dtype: int64

In [85]:
# drop irrelevant columns
columns_to_drop = ['Unnamed: 0','Pokemon', 'Card Type', 'Generation', 'Card Number', 'Price', 'ranks', 'title', 'no_of_reviews', 'ratings', 'author', 'cover_type', 'year', 'genre', 'date', 'product', 'market', 'size']
df = data.drop(columns=columns_to_drop)
df

,Unnamed: 0.1,item_id,name,category,price,old_price,sellable_online,link,other_colors,short_description,designer,depth,height,width
0,0,90420332.0,FREKVENS,Bar furniture,265.0,No old price,True,https://www.ikea.com/sa/en/p/frekvens-bar-tabl...,No,"Bar table, in/outdoor, 51x51 cm",Nicholai Wiig Hansen,NaN,99.0,51.0
1,1,368814.0,NORDVIKEN,Bar furniture,995.0,No old price,False,https://www.ikea.com/sa/en/p/nordviken-bar-tab...,No,"Bar table, 140x80 cm",Francis Cayouette,NaN,105.0,80.0
2,2,9333523.0,NORDVIKEN / NORDVIKEN,Bar furniture,2095.0,No old price,False,https://www.ikea.com/sa/en/p/nordviken-nordvik...,No,Bar table and 4 bar stools,Francis Cayouette,NaN,NaN,NaN
3,3,80155205.0,STIG,Bar furniture,69.0,No old price,True,https://www.ikea.com/sa/en/p/stig-bar-stool-wi...,Yes,"Bar stool with backrest, 74 cm",Henrik Preutz,50.0,100.0,60.0
4,4,30180504.0,NORBERG,Bar furniture,225.0,No old price,True,https://www.ikea.com/sa/en/p/norberg-wall-moun...,No,"Wall-mounted drop-leaf table, ...",Marcus Arvonen,60.0,43.0,74.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92510,61927,NaN,NaN,NaN,3099.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92511,61928,NaN,NaN,NaN,3100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92512,61929,NaN,NaN,NaN,3100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92513,61930,NaN,NaN,NaN,2900.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92514,61931,NaN,NaN,NaN,3000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

I decided to only keep the data that is relevant to ikea products. I dropped the column 'Unnamed: 0' because it contained a lot of NaN values and had no purpose in this data. I also dropped all the columns that were irrelevant such as pokemon, card type and everything related to pokemon. There were also two columns named price so I dropped that as well.

In [106]:
# Rename columns
ikea = df.rename(columns={
    'Unnamed: 0.1': 'Index',
    'item_id': 'Item_id',
    'name': 'Product_Name',
    'category': 'Product_Category',
    'price': 'Price',
    'old_price': 'Old_Price',
    'sellable_online': 'Sellable_Online',
    'link': 'Product_Link',
    'other_colors': 'Other_Colors',
    'short_description': 'Product_Description',
    'designer': 'Designer',
    'depth': 'Product_Depth',
    'height': 'Product_Height',
    'width': 'Product_Width'
})
ikea

,Index,Item_id,Product_Name,Product_Category,Price,Old_Price,Sellable_Online,Product_Link,Other_Colors,Product_Description,Designer,Product_Depth,Product_Height,Product_Width
0,0,90420332.0,FREKVENS,Bar furniture,265.0,No old price,True,https://www.ikea.com/sa/en/p/frekvens-bar-tabl...,No,"Bar table, in/outdoor, 51x51 cm",Nicholai Wiig Hansen,NaN,99.0,51.0
1,1,368814.0,NORDVIKEN,Bar furniture,995.0,No old price,False,https://www.ikea.com/sa/en/p/nordviken-bar-tab...,No,"Bar table, 140x80 cm",Francis Cayouette,NaN,105.0,80.0
2,2,9333523.0,NORDVIKEN / NORDVIKEN,Bar furniture,2095.0,No old price,False,https://www.ikea.com/sa/en/p/nordviken-nordvik...,No,Bar table and 4 bar stools,Francis Cayouette,NaN,NaN,NaN
3,3,80155205.0,STIG,Bar furniture,69.0,No old price,True,https://www.ikea.com/sa/en/p/stig-bar-stool-wi...,Yes,"Bar stool with backrest, 74 cm",Henrik Preutz,50.0,100.0,60.0
4,4,30180504.0,NORBERG,Bar furniture,225.0,No old price,True,https://www.ikea.com/sa/en/p/norberg-wall-moun...,No,"Wall-mounted drop-leaf table, ...",Marcus Arvonen,60.0,43.0,74.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92510,61927,NaN,NaN,NaN,3099.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92511,61928,NaN,NaN,NaN,3100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92512,61929,NaN,NaN,NaN,3100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92513,61930,NaN,NaN,NaN,2900.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92514,61931,NaN,NaN,NaN,3000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

For this portion, I created a new DataFrame called ikea and renamed all the columns and capitalized the first letter so it looks clean and easier to read.

In [107]:
# drop any rows containing NaN values
ikea.dropna(how = 'any')

,Index,Item_id,Product_Name,Product_Category,Price,Old_Price,Sellable_Online,Product_Link,Other_Colors,Product_Description,Designer,Product_Depth,Product_Height,Product_Width
3,3,80155205.0,STIG,Bar furniture,69.0,No old price,True,https://www.ikea.com/sa/en/p/stig-bar-stool-wi...,Yes,"Bar stool with backrest, 74 cm",Henrik Preutz,50.0,100.0,60.0
4,4,30180504.0,NORBERG,Bar furniture,225.0,No old price,True,https://www.ikea.com/sa/en/p/norberg-wall-moun...,No,"Wall-mounted drop-leaf table, ...",Marcus Arvonen,60.0,43.0,74.0
5,5,10122647.0,INGOLF,Bar furniture,345.0,No old price,True,https://www.ikea.com/sa/en/p/ingolf-bar-stool-...,No,"Bar stool with backrest, 63 cm",Carina Bengs,45.0,91.0,40.0
6,6,70404875.0,FRANKLIN,Bar furniture,129.0,No old price,True,https://www.ikea.com/sa/en/p/franklin-bar-stoo...,No,"Bar stool with backrest, foldable, ...",K Hagberg/M Hagberg,44.0,95.0,50.0
8,8,50406465.0,FRANKLIN,Bar furniture,129.0,No old price,True,https://www.ikea.com/sa/en/p/franklin-bar-stoo...,No,"Bar stool with backrest, foldable, ...",K Hagberg/M Hagberg,44.0,95.0,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3683,3683,39329299.0,PAX / FORSAND/VIKEDAL,Wardrobes,1260.0,No old price,True,https://www.ikea.com/sa/en/p/pax-forsand-viked...,Yes,"Wardrobe combination, 75x60x2...",Ehlén Johansson/IKEA of Sweden,60.0,201.0,75.0
3684,3684,49157565.0,ELVARLI,Wardrobes,1245.0,"SR 1,735",True,https://www.ikea.com/sa/en/p/elvarli-2-section...,No,"2 sections, 165x55x216 cm",Ehlén Johansson/IKEA of Sweden,55.0,216.0,164.0
3685,3685,59324936.0,PAX / FORSAND,Wardrobes,2100.0,No old price,True,https://www.ikea.com/sa/en/p/pax-forsand-wardr...,Yes,"Wardrobe combination, 100x60x...",IKEA of Sweden/Ehlén Johansson,60.0,236.0,100.0
3686,3686,69330475.0,PAX / HOKKSUND,Wardrobes,3985.0,No old price,True,https://www.ikea.com/sa/en/p/pax-hokksund-ward...,No,"Wardrobe combination, 150x66x...",IKEA of Sweden/Ehlén Johansson,66.0,236.0,150.0
3688,3688,89330653.0,PAX / MEHAMN/AULI,Wardrobes,2045.0,No old price,True,https://www.ikea.com/sa/en/p/pax-mehamn-auli-w...,No,"Wardrobe combination, 200x66x...",IKEA of Sweden/Ehlén Johansson,66.0,236.0,200.0

For this portion, I removed any rows that contained missing values.

In [109]:
ikea = ikea.dropna(subset=float_columns)
ikea[float_columns] = ikea[float_columns].astype(int)

In [110]:
ikea[float_columns] = ikea[float_columns].fillna(0).astype(int)
ikea[float_columns]

       Item_id  Price  Product_Depth  Product_Height  Product_Width
3     80155205     69             50             100             60
4     30180504    225             60              43             74
5     10122647    345             45              91             40
6     70404875    129             44              95             50
8     50406465    129             44              95             50
...        ...    ...            ...             ...            ...
3683  39329299   1260             60             201             75
3684  49157565   1245             55             216            164
3685  59324936   2100             60             236            100
3686  69330475   3985             66             236            150
3688  89330653   2045             66             236            200

[1899 rows x 5 columns]

For this portion, almost all the rows with numerical values have float values. So I converted those columns into int datatype.

In [94]:
ikea

,Index,Item_id,Product_Name,Product_Category,Price,Old_Price,Sellable_Online,Product_Link,Other_Colors,Product_Description,Product_Designer,Product_Depth,Product_Height,Product_Width
3,3,80155205,STIG,Bar furniture,69,No old price,True,https://www.ikea.com/sa/en/p/stig-bar-stool-wi...,Yes,"Bar stool with backrest, 74 cm",Henrik Preutz,50,100,60
4,4,30180504,NORBERG,Bar furniture,225,No old price,True,https://www.ikea.com/sa/en/p/norberg-wall-moun...,No,"Wall-mounted drop-leaf table, ...",Marcus Arvonen,60,43,74
5,5,10122647,INGOLF,Bar furniture,345,No old price,True,https://www.ikea.com/sa/en/p/ingolf-bar-stool-...,No,"Bar stool with backrest, 63 cm",Carina Bengs,45,91,40
6,6,70404875,FRANKLIN,Bar furniture,129,No old price,True,https://www.ikea.com/sa/en/p/franklin-bar-stoo...,No,"Bar stool with backrest, foldable, ...",K Hagberg/M Hagberg,44,95,50
8,8,50406465,FRANKLIN,Bar furniture,129,No old price,True,https://www.ikea.com/sa/en/p/franklin-bar-stoo...,No,"Bar stool with backrest, foldable, ...",K Hagberg/M Hagberg,44,95,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3683,3683,39329299,PAX / FORSAND/VIKEDAL,Wardrobes,1260,No old price,True,https://www.ikea.com/sa/en/p/pax-forsand-viked...,Yes,"Wardrobe combination, 75x60x2...",Ehlén Johansson/IKEA of Sweden,60,201,75
3684,3684,49157565,ELVARLI,Wardrobes,1245,"SR 1,735",True,https://www.ikea.com/sa/en/p/elvarli-2-section...,No,"2 sections, 165x55x216 cm",Ehlén Johansson/IKEA of Sweden,55,216,164
3685,3685,59324936,PAX / FORSAND,Wardrobes,2100,No old price,True,https://www.ikea.com/sa/en/p/pax-forsand-wardr...,Yes,"Wardrobe combination, 100x60x...",IKEA of Sweden/Ehlén Johansson,60,236,100
3686,3686,69330475,PAX / HOKKSUND,Wardrobes,3985,No old price,True,https://www.ikea.com/sa/en/p/pax-hokksund-ward...,No,"Wardrobe combination, 150x66x...",IKEA of Sweden/Ehlén Johansson,66,236,150
3688,3688,89330653,PAX / MEHAMN/AULI,Wardrobes,2045,No old price,True,https://www.ikea.com/sa/en/p/pax-mehamn-auli-w...,No,"Wardrobe combination, 200x66x...",IKEA of Sweden/Ehlén Johansson,66,236,200

In [113]:
ikea['Designer']

3                        Henrik Preutz
4                       Marcus Arvonen
5                         Carina Bengs
6                  K Hagberg/M Hagberg
8                  K Hagberg/M Hagberg
                     ...
3683    Ehlén Johansson/IKEA of Sweden
3684    Ehlén Johansson/IKEA of Sweden
3685    IKEA of Sweden/Ehlén Johansson
3686    IKEA of Sweden/Ehlén Johansson
3688    IKEA of Sweden/Ehlén Johansson
Name: Designer, Length: 1899, dtype: object

During the analysis, I discovered that the designer column has inconsistent data. It includes the name of the designer and description of some products. One approach to consider for this issue is using regex pattern. Unfortunately due to large amount of data to filter, it will be time consuming. So, I decided to explore this issue outside of this project. This will allow me to learn more about regex.

In [116]:
new_data.to_csv('cleaned_data_lake.csv', index=False)